name: open-tic-tac-toe
summary: Open Tic Tac Toe is a free and open source game to run on Linux systems.
description: |
  Open Tic Tac Toe is a free and open source game developed by Junior Criste to run on Linux systems.
Open Tic Tac Toe é um "jogo da velha" gratuito e de código aberto desenvolvido por Junior Criste para rodar em sistemas Linux.
version: '2.0'
confinement: strict

apps:
  open-tic-tac-toe:
    command: open-tic-tac-toe

parts:
  open-tic-tac-toe:
    plugin: dump
    source: https://github.com/JuniorCriste/Open-TIC-TAC-TOE/raw/master/bin/opentictactoe-2.0.tar.gz
   build-packages:
    - gambas3


plugs:
  open-tic-tac-toe-home:
    interface: home
  open-tic-tac-toe-network:
    interface: network
  open-tic-tac-toe-system-files:
    interface: system-files
